// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // static FirebaseOptions get currentPlatform {
  //   if (kIsWeb) {
  //     return web;
  //   }
  //   switch (defaultTargetPlatform) {
  //     case TargetPlatform.android:
  //       return android;
  //     case TargetPlatform.iOS:
  //       return ios;
  //     case TargetPlatform.macOS:
  //       return macos;
  //     case TargetPlatform.windows:
  //       return windows;
  //     case TargetPlatform.linux:
  //       throw UnsupportedError(
  //         'DefaultFirebaseOptions have not been configured for linux - '
  //         'you can reconfigure this by running the FlutterFire CLI again.',
  //       );
  //     default:
  //       throw UnsupportedError(
  //         'DefaultFirebaseOptions are not supported for this platform.',
  //       );
  //   }
  // }



  static const FirebaseOptions android = FirebaseOptions(
apiKey: "AIzaSyD0xH_C5LyN7suQEMEHpdrGR5GvOYEDzrE",
  authDomain: "only-vocal-app.firebaseapp.com",
  projectId: "only-vocal-app",
  storageBucket: "only-vocal-app.firebasestorage.app",
  messagingSenderId: "991581469059",
  appId: "1:991581469059:web:e3736a4ebffb6f45bc9eb6"
  );

  
}
