// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyD0xH_C5LyN7suQEMEHpdrGR5GvOYEDzrE",
    authDomain: "only-vocal-app.firebaseapp.com",
    projectId: "only-vocal-app",
    storageBucket: "only-vocal-app.firebasestorage.app",
    messagingSenderId: "991581469059",
    appId: "1:991581469059:web:e3736a4ebffb6f45bc9eb6"
  );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyAS6Nro1We6mMSevTmlWM1164iJpoJdXfc',
  //   appId: '1:794991610109:android:35ea566641ba07db5f1694',
  //   messagingSenderId: '794991610109',
  //   projectId: 'music-player-58d31',
  //   storageBucket: 'music-player-58d31.appspot.com',
  // );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5tC3gll9FuA2VoUjaA7PNFvaun35tk_M',
    appId: '1:991581469059:ios:1a2a7e8b91b0247cbc9eb6',
    messagingSenderId: '991581469059',
    projectId: 'only-vocal-app',
    storageBucket: 'only-vocal-app.firebasestorage.app',
    iosBundleId: 'com.example.onlyVocal',
  );



  static const FirebaseOptions android = FirebaseOptions(
  apiKey: "AIzaSyD0xH_C5LyN7suQEMEHpdrGR5GvOYEDzrE",
    authDomain: "only-vocal-app.firebaseapp.com",
    projectId: "only-vocal-app",
    storageBucket: "only-vocal-app.firebasestorage.app",
    messagingSenderId: "991581469059",
    appId: "1:991581469059:web:e3736a4ebffb6f45bc9eb6"
    );

  
}
